### ISSUE TITLE
requiring seaborn and sympy

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsbeams#24]
I see that seaborn is used in radiasoft_rc.ipynb, but I don't see it used by rsbeams itself.

sympy is used in one module, and I'm wondering if that's needed by sirepo.

Both these packages are very large. seaborn is small, but it requires pandas so that's about 35MB. sympy is 30MB. 

Just trying to get a handle on dependencies.

**Comment by cchall** [comment]
I'm not sure about seaborn. @ncook882 has set up the plotting modules in the past I think.

I use the Beamline module quite a bit, but I doubt it or sympy are needed by sirepo.
